version: '3'
services:
  open3d-gui:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri
    ipc: host

